name: 'Build'
description: 'Combines checkout, openjdk17 install, setup-gradle, and gradle build into one'
inputs:
  gradle-encryption-key:
    description: 'The encryption key to use for caching'
    required: true
  github-user:
    description: 'GitHub username for authentication'
    required: true
  github-token:
    description: 'GitHub token for authentication'
    required: true
runs:
  using: "composite"
  steps:
  - name: Install Git
    run: |
      sudo apt-get update
      sudo apt-get install -y git
      git --version
    shell: bash
  - name: set up JDK
    uses: actions/setup-java@v4.2.1
    with:
      java-version: '17.0'
      distribution: 'temurin'
      cache: gradle
  - name: Setup Gradle
    uses: gradle/actions/setup-gradle@v3.3.2
    with:
      gradle-version: 8.6
      cache-encryption-key: ${{ inputs.gradle-encryption-key }}
      cache-read-only: false
      cache-overwrite-existing: true
  - name: Build with Gradle
    run: ./gradlew build
    shell: bash
    env:
      GITHUB_USER: ${{ inputs.github-user }}
      GITHUB_TOKEN: ${{ inputs.github-token }}
