name: Automated Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: 'true'
    - name: Build
      with:
        gradle-encryption-key: ${{ secrets.GradleEncryptionKey }}
      uses: ./.github/actions/build-apk
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ github.workspace }}/apps/basicSubscriber/build/outputs/apk/debug/basicSubscriber-debug.apk
          ${{ github.workspace }}/apps/basicSubscriber/build/outputs/apk/release/basicSubscriber-release-unsigned.apk
          ${{ github.workspace }}/apps/basicAssembler/build/outputs/apk/debug/basicAssembler-debug.apk
          ${{ github.workspace }}/apps/basicAssembler/build/outputs/apk/release/basicAssembler-release-unsigned.apk
          ${{ github.workspace }}/apps/backAndForth/build/outputs/apk/debug/backAndForth-debug.apk
          ${{ github.workspace }}/apps/backAndForth/build/outputs/apk/release/backAndForth-release-unsigned.apk
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ github.ref_name }}
        generate_release_notes: true
