name: Build Check

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: 'true'
    - name: Build
      with:
        gradle-encryption-key: ${{ secrets.GradleEncryptionKey }}
      uses: ./.github/actions/build-apk
